openapi: 3.0.0
info:
  title: T-shirt store
  description: A t-shirt store app
  version: 1.0.0

# servers:
#   - url: http://localhost:4000/api/v1
#     description: Optional server description, e.g. Main (production) server
#   - url: http://staging-api.example.com
#     description: Optional server description, e.g. Internal staging server for testing

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: Optional server description, e.g. Main (production) server
    variables:
      version:
        default: v1
        enum:
         - v1
         - v2
      protocol:
        default: http
        enum:
          - "http"
          - "https"
components:
  securitySchemes:
    cookie: 
      name: My Auth
      type: apiKey
      in: cookie
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /:
    get:
      summary: returns home data
      tags:
        - "Home"
      responses:
        '200':
          description: returns an object
          content: 
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  message:
                    type: string
                  
